default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: <%= APP_ENV['development']['database_db'] %>
  username: <%= APP_ENV['development']['database_user'] %>
  password: <%= "\#{APP_ENV['development']['database_pass']}" %>
  host: <%= APP_ENV['development']['database_host'] %>
  schema_search_path: <%= APP_ENV['development']['database_schema'] %>

production:
  <<: *default
  database: <%= APP_ENV['development']['database_db'] %>
  username: <%= APP_ENV['development']['database_user'] %>
  password: <%= "\#{APP_ENV['development']['database_pass']}" %>
  host: <%= APP_ENV['development']['database_host'] %>
  schema_search_path: <%= APP_ENV['development']['database_schema'] %>

test:
  <<: *default
  database: <%= APP_ENV['development']['database_db'] %>
  username: <%= APP_ENV['development']['database_user'] %>
  password: <%= APP_ENV['development']['database_user'] %>
  host: <%= APP_ENV['development']['database_host'] %>
  schema_search_path: <%= APP_ENV['development']['database_schema'] %>
